openapi: 3.0.3
info:
  title: E-Commerce Backend API
  description: Microservices-based e-commerce platform
  version: 1.0.0
  contact:
    name: API Support
    email: support@ecommerce.example.com

servers:
  - url: http://localhost:3000
    description: Order Service
  - url: http://localhost:3001
    description: Payment Service
  - url: http://localhost:3002
    description: Notification Service
  - url: http://localhost:3003
    description: Review Service
  - url: http://localhost:3004
    description: Search Service

tags:
  - name: Orders
    description: Order management
  - name: Payments
    description: Payment processing
  - name: Notifications
    description: User notifications
  - name: Reviews
    description: Product reviews
  - name: Search
    description: Product search

paths:
  /api/v1/orders:
    post:
      tags:
        - Orders
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - items
              properties:
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - productId
                      - quantity
                      - price
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
                        minimum: 1
                      price:
                        type: number
                        minimum: 0
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid request

  /api/v1/orders/{id}:
    get:
      tags:
        - Orders
      summary: Get order by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found

  /api/v1/orders/{id}/status:
    patch:
      tags:
        - Orders
      summary: Update order status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum: [pending, reserved, paid, shipped, delivered, cancelled]
      responses:
        '200':
          description: Status updated
        '404':
          description: Order not found

  /api/v1/payments:
    post:
      tags:
        - Payments
      summary: Create a payment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - orderId
                - amount
                - paymentMethod
              properties:
                orderId:
                  type: string
                amount:
                  type: number
                  minimum: 0
                currency:
                  type: string
                  default: USD
                paymentMethod:
                  type: string
                  enum: [card, upi, wallet, netbanking]
                simulationParams:
                  type: object
                  properties:
                    shouldFail:
                      type: boolean
                    delayMs:
                      type: integer
                      minimum: 0
                      maximum: 30000
      responses:
        '201':
          description: Payment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment'

  /api/v1/payments/webhook:
    post:
      tags:
        - Payments
      summary: Process payment webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - transactionId
                - status
              properties:
                transactionId:
                  type: string
                status:
                  type: string
                  enum: [success, failed]
      responses:
        '200':
          description: Webhook processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  duplicate:
                    type: boolean

  /api/v1/notifications/user/{userId}:
    get:
      tags:
        - Notifications
      summary: Get user notifications
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: skip
          in: query
          schema:
            type: integer
            default: 0
        - name: unreadOnly
          in: query
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: User notifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
                  total:
                    type: integer
                  limit:
                    type: integer
                  skip:
                    type: integer

  /api/v1/reviews:
    post:
      tags:
        - Reviews
      summary: Create a product review
      parameters:
        - name: x-user-id
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - productId
                - rating
                - comment
              properties:
                productId:
                  type: string
                rating:
                  type: integer
                  minimum: 1
                  maximum: 5
                comment:
                  type: string
                  maxLength: 1000
      responses:
        '201':
          description: Review created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'

  /api/v1/reviews/product/{productId}:
    get:
      tags:
        - Reviews
      summary: Get product reviews
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: skip
          in: query
          schema:
            type: integer
            default: 0
        - name: sortBy
          in: query
          schema:
            type: string
            enum: [createdAt, rating]
            default: createdAt
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        '200':
          description: Product reviews
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviews:
                    type: array
                    items:
                      $ref: '#/components/schemas/Review'
                  total:
                    type: integer
                  averageRating:
                    type: number
                  limit:
                    type: integer
                  skip:
                    type: integer

  /api/v1/reviews/{id}:
    delete:
      tags:
        - Reviews
      summary: Delete a review (admin only)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: x-admin
          in: header
          required: true
          schema:
            type: string
            enum: ['true']
      responses:
        '204':
          description: Review deleted
        '404':
          description: Review not found

  /api/v1/search:
    get:
      tags:
        - Search
      summary: Search products
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Search results
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  total:
                    type: integer

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        status:
          type: string
          enum: [pending, reserved, paid, shipped, delivered, cancelled]
        items:
          type: array
          items:
            type: object
            properties:
              productId:
                type: string
              quantity:
                type: integer
              price:
                type: number
        totalAmount:
          type: number
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    Payment:
      type: object
      properties:
        id:
          type: string
        orderId:
          type: string
        transactionId:
          type: string
        amount:
          type: number
        currency:
          type: string
        paymentMethod:
          type: string
        status:
          type: string
          enum: [pending, success, failed]
        createdAt:
          type: string
          format: date-time

    Notification:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        type:
          type: string
          enum: [order_created, payment_success, payment_failed]
        title:
          type: string
        message:
          type: string
        read:
          type: boolean
        metadata:
          type: object
        createdAt:
          type: string
          format: date-time

    Review:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        userId:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string
        createdAt:
          type: string
          format: date-time

    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        category:
          type: string
        stock:
          type: integer
