version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_broker
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672' # RabbitMQ Dashboard

volumes:
  mongo_data:
