version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    ports:
      - "5002:5001"
    env_file:
      - ./services/user-service/.env
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/user-service
      - JWT_SECRET=supersecret
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - kafka

  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile
    container_name: product-service
    restart: unless-stopped
    ports:
      - "5003:5002"
    env_file:
      - ./services/product-service/.env
    environment:
      - NODE_ENV=development
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/product-service
      - JWT_SECRET=supersecret
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - user-service
      - kafka

  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./services/order-service/.env
    environment:
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - mongo
      - redis
      - kafka
      - product-service
      - user-service

volumes:
  mongo-data:
